</section>
	<footer>
		<div class="firma">
			
		</div>
		<div class="datos_contacto">
			<address>
				<span class="icon-phone3"></span>
			</address>
			<address>
				<span class="icon-mail3"></span>
			</address>
			<address> 
				<span class="icon-office"></span>
			</address>
		</div>
	</footer>
	<span class="goheaven icon-arrow-up4"></span>
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="js/jquery-1.11.1.min.js"></script>
	<script src="js/jquery.slides.js"></script>
	<script src="js/slider.js"></script>
	<script src="js/main.js"></script>

	<!--Google Analytics-->
	<script>
  		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 		ga('create', 'UA-56646324-1', 'auto');
  		ga('send', 'pageview');
	</script>
</body>    