<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8" />
	<meta name="author" content="spert" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<meta name="description" content="SPERT S.A. de C.V. " />
	<meta name="keywords" content="" />
	<link rel="stylesheet" href="estilo/normalize.css" />
	<link rel="stylesheet" href="estilo/estilos.css" />
	<link rel="stylesheet" href="fonts/fonts.css" />
	<link rel="icon" type="image/x-icon" href="./images/fav.ico" />
	<!--[if lt IE 9]><script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script><![endif]-->
	<title>REDOT | Servicios Tecnológicos</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/> 
</head>
<body>
	<header>
		<div class="menu_bar">
			<a href="#" class="bt-menu"><img src="images/circ.png" alt="REDOT Servicios Tecnológicos"><span class="icon-menu"></span></a>
		</div>
		<nav>
			<div class="social">
				<ul>
					<li><a href="#"><span class="icon-googleplus3"></span></a></li>
					<li><a href="https://www.facebook.com/redot.mexico"><span class="icon-facebook3"></span></a></li>
					<li><a href="#"><span class="icon-linkedin2"></span></a></li>
				</ul>
			</div>
			<ul>
				<li class="logo"><a href="/redot"><img src="images/logo.png" alt="REDOT Servicios Tecnológicos"></a></li>
				<li><a href="/redot"><span class="icon-home3"></span>Inicio</a></li>
				<li><a href="#"><span class="icon-user3"></span>Nosotros</a></li>
				<li class="submenu">
					<a href="#"><span class="icon-pawn"></span>Áreas de Negocio <span class="icon-arrow-down4"></span></a>
					<ul class="children">
						<li><a href="#"><span class="icon-console"></span>Desarrollo a la Medida</a></li>
						<li><a href="#"><span class="icon-mobile"></span>Desarrollo Móvil</a></li>
						<li><a href="#"><span class="icon-thumbs-up"></span>Marketing Digital</a></li>
						<li><a href="#"><span class="icon-tools"></span>Soporte y Mantenimiento</a></li>
					</ul>
				</li>
				<li><a href="#"><span class="icon-cogs"></span>Soluciones</a></li>
				<li><a href="./contact_us.php"><span class="icon-phone"></span>Contacto</a></li>
			</ul>
		</nav>
	</header>
	<section>
		